services:
  web_framework_db:
    image: mariadb:11.8
    container_name: web_framework_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: 'web_framework'
      MARIADB_USER: 'web_framework'
      MARIADB_PASSWORD: 'testpassword'
      MARIADB_ROOT_PASSWORD: 'testpassword'
      MARIADB_AUTO_UPGRADE: true
    ports:
      - 127.0.0.1:3399:3306
    volumes:
      - ./db_web_framework/:/var/lib/mysql/
  web_framework_redis:
    image: bitnami/redis
    container_name: web_framework_redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: 'testpassword'
    ports:
      - 127.0.0.1:3400:6379
